name: main
on:
  push:
    branches:
      - 'master'
#   pull_request:
#     types:
#       - closed
#     branches:
#       - 'master'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello 
